//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse_Proyect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CategoriaProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaProducto()
        {
            this.Producto = new HashSet<Producto>();
        }
        
        [Display( Name = "IdCatProd")]
        public int idCatProd { get; set; }

        [Display(Name = "Nombre")]
        [Required]
        [StringLength(45, ErrorMessage = "Tamaño máximo de 45 caracteres")]
        public string nombre { get; set; }

        [Display(Name = "Descripcion")]
        [Required]
        [StringLength(100, ErrorMessage = "Tamaño máximo de 100 caracteres")]
        public string descripcion { get; set; }

        [Display(Name = "Estado")]
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
